### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by raphaelshirley** [herjy/MuSCADeT#2]
Hi,

Thank you very much for making your code available to use. I am trying to run your examples with a view to using the code as part of an effort to combine deblending methods we are making at the University of Sussex Astronomy Centre. 

After seemingly installing the package successfully I get the following error on running the first example:

mps017431:Examples rs548$ python Example_simple.py 
Traceback (most recent call last):
  File "Example_simple.py", line 5, in <module>
    from MuSCADeT import MCA
  File "/Users/rs548/anaconda/lib/python3.5/site-packages/MuSCADeT-0.1-py3.5.egg/MuSCADeT/**init**.py", line 1, in <module>
    import MCA
ImportError: No module named 'MCA'

I think this may be related to the debate about whether it is best to leave **init**.py empty or to import modules there. Do you know a way to fix this error. If I run **init**.py it has no trouble importing the modules from its directory but when running the full code it fails for some reason.

Many thanks,

Dr Raphael Shirley
University of Sussex
raphael.shirley@sussex.ac.uk

**Comment by herjy** [comment]
Hi Shirley, thanks for the feedback, it must be due to the most recent changes, I think I tried to rename a few things for clarity and I might have forgotten to update a few things. Thanks for the input. I'll deal with it by the end of the day and come back to you. 

Nice to hear about your work on deblending! I hope my code will be of use to you!

**Comment by herjy** [comment]
Hi Raphael (sorry for the confusion),
I am having trouble replicating your bug. Could you please tell me more about what OS you are using and how you installed it please? did you use:
python setup.py install ?

Also I am new to packaging. What the issue you are refering to with the init? Maybe in the _init_.py replacing "from MCA import *" by "import MCA" could do the trick, but I can't try it myself since I can't replicate the bug. 

Thanks in advance for the info.

**Comment by raphaelshirley** [comment]
Hello,

Sorry for the delay in replying, I have been away from work for a couple of days. I have MuSCADeT importing without errors now. I think this is probably because I switched to Python 2.7 (from 3.5). I will try and run the examples and get to know the software over the next few days.

Many thanks,

Raphael.

**Comment by raphaelshirley** [comment]
FYI I am on a mac and installed using python setup.py install. Perhaps different versions of python handle **init**.py differently?

**Comment by herjy** [comment]
Hi Raphael, 
Thanks for the feed bak. Glad to know that it works now! 
Indeed, I'm not sure it runs with python version >2.7. I have never tested it for other versions. Let me know if it finally works, I will add a comment in the readme. 
Just as an indication, there are a few bugs reported that I haven't had time to fix yet, but will soon. Most of them actually arise if you use image smaller than 64x64 pixels, just so you know. I will try to fix these asap. Let me know if you have any other problem and good luck with your research, I am always glad to hear that the algorithm is used for new applications,

Rémy

**Comment by herjy** [comment]
Also, you might want to download the last version I've pushed yesterday, I fixed a bug. The last version should runs on the examples.
